<?php

namespace App\Services\Tribunal;

use App\Enums\TribunalDecisionStatus;
use App\Models\TribunalCase;
use App\Models\TribunalCaseEvent;
use App\Models\TribunalCaseReport;
use App\Models\TribunalCaseReportDownload;
use App\Models\TribunalDecision;
use App\Models\User;
use Barryvdh\DomPDF\Facade\Pdf;
use Illuminate\Http\UploadedFile;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Str;
use SimpleSoftwareIO\QrCode\Facades\QrCode;
use Symfony\Component\HttpFoundation\BinaryFileResponse;

class TribunalReportService
{
    /**
     * Authorize user for report generation and download.
     * Allowed:
     * - Complainant
     * - Respondent
     * - Active Complainant Lawyer
     * - Active Respondent Lawyer
     * - Super Admin
     * All others (unassigned, jury panel, unrelated lawyers, other users): 403
     */
    public function authorizeUser(TribunalCase $case, int $userId): void
    {
        $user = User::find($userId);
        if (!$user) {
            abort(401, 'Unauthenticated.');
        }

        // 1. Super Admin
        if ($user->is_admin) {
            return;
        }

        // 2. Complainant
        if ($case->isComplainant($userId)) {
            return;
        }

        // 3. Respondent
        if ($case->isRespondent($userId)) {
            return;
        }

        // 4. Current Active Legal Representatives
        $activeRep = $case->activeRepresentativeAssignments()
            ->where('representative_user_id', $userId)
            ->first();

        if ($activeRep) {
            if ($case->isComplainant($activeRep->client_user_id) || $case->isRespondent($activeRep->client_user_id)) {
                return;
            }
        }

        abort(403, 'Unauthorized. Official Tribunal reports are restricted to authorized case participants.');
    }

    /**
     * Generate or retrieve official final Tribunal report.
     */
    public function generateFinalReport(TribunalCase $case, int $userId, bool $forceRegenerate = false): TribunalCaseReport
    {
        // 1. Authorize
        $this->authorizeUser($case, $userId);

        // 2. Validate Final Decision Exists and is Final
        $decision = $case->finalDecision;
        if (!$decision || !$decision->isFinal()) {
            abort(422, 'Official report can only be generated after a final Tribunal decision has been published.');
        }

        // 3. Check for existing generated report
        $existingReport = $case->reports()
            ->where('status', 'generated')
            ->orderByDesc('version')
            ->first();

        if ($existingReport && !$forceRegenerate) {
            return $existingReport;
        }

        // 4. Atomic generation transaction
        return DB::transaction(function () use ($case, $decision, $userId, $existingReport) {
            $reportNumber = $this->generateReportNumber();
            $verificationCode = $this->generateVerificationCode();
            $version = $existingReport ? ($existingReport->version + 1) : 1;

            if ($existingReport) {
                $existingReport->update(['status' => 'superseded']);
            }

            // QR Code generation
            $verifyBaseUrl = config('tribunal.report_verify_url', 'http://localhost:5173/tribunal/reports/verify');
            $verifyUrl = rtrim($verifyBaseUrl, '/') . '/' . $verificationCode;
            $qrSvg = QrCode::format('svg')->size(110)->margin(1)->generate($verifyUrl);
            $qrDataUri = 'data:image/svg+xml;base64,' . base64_encode($qrSvg);

            $issuedAt = now();

            // Build safe dossier (Strict whitelist, NO private deliberations or notes)
            $dossier = $this->buildDossier(
                $case,
                $decision,
                $reportNumber,
                $verificationCode,
                $qrDataUri,
                $verifyUrl,
                $version,
                $issuedAt
            );

            // Render PDF with Dompdf
            $pdf = Pdf::loadView('tribunal.reports.final-decision', $dossier);
            $pdf->setPaper('a4', 'portrait');
            $pdf->setOption('isHtml5ParserEnabled', true);
            $pdf->setOption('isRemoteEnabled', false);
            $pdfContent = $pdf->output();

            // Calculate SHA-256 hash of generated bytes
            $fileHash = hash('sha256', $pdfContent);

            // Store in private storage
            $filePath = "tribunal/reports/{$case->id}/{$reportNumber}.pdf";
            Storage::disk('local')->put($filePath, $pdfContent);

            // Create report DB record
            $report = TribunalCaseReport::create([
                'tribunal_case_id' => $case->id,
                'tribunal_decision_id' => $decision->id,
                'report_number' => $reportNumber,
                'verification_code' => $verificationCode,
                'report_type' => 'final_decision_report',
                'status' => 'generated',
                'version' => $version,
                'file_path' => $filePath,
                'file_hash' => $fileHash,
                'issued_at' => $issuedAt,
                'generated_by_user_id' => $userId,
                'generated_at' => $issuedAt,
                'download_count' => 0,
            ]);

            // Audit generation via TribunalCaseEventService
            TribunalCaseEventService::log(
                $case,
                $existingReport ? 'tribunal_report_regenerated' : 'tribunal_report_generated',
                $userId,
                [
                    'report_id' => $report->id,
                    'report_number' => $report->report_number,
                    'version' => $report->version,
                    'verification_code' => $report->verification_code,
                    'file_hash' => $report->file_hash,
                ]
            );

            return $report;
        });
    }

    /**
     * Download official report file with authorization and audit logging.
     */
    public function downloadReport(
        TribunalCaseReport $report,
        int $userId,
        ?string $ipAddress = null,
        ?string $userAgent = null
    ): BinaryFileResponse {
        $case = $report->case;
        $this->authorizeUser($case, $userId);

        if (!Storage::disk('local')->exists($report->file_path)) {
            abort(404, 'Official report document file could not be located in secure storage.');
        }

        // Record download audit
        TribunalCaseReportDownload::create([
            'tribunal_case_report_id' => $report->id,
            'downloaded_by_user_id' => $userId,
            'downloaded_at' => now(),
            'ip_address' => $ipAddress,
            'user_agent' => $userAgent ? Str::limit($userAgent, 500) : null,
        ]);

        $report->increment('download_count');
        $report->update(['last_downloaded_at' => now()]);

        // Audit via TribunalCaseEventService
        TribunalCaseEventService::log(
            $case,
            'tribunal_report_downloaded',
            $userId,
            [
                'report_id' => $report->id,
                'report_number' => $report->report_number,
                'version' => $report->version,
                'download_count' => $report->download_count,
            ]
        );

        $fullPath = Storage::disk('local')->path($report->file_path);
        $downloadFilename = "{$report->report_number}.pdf";

        return response()->download($fullPath, $downloadFilename, [
            'Content-Type' => 'application/pdf',
            'Content-Disposition' => "attachment; filename=\"{$downloadFilename}\"",
        ]);
    }

    /**
     * Verify report by verification code or report number.
     */
    public function verifyCode(string $code): array
    {
        $cleanCode = trim(strtoupper($code));

        $report = TribunalCaseReport::with(['case', 'decision', 'decision.juryPanel'])
            ->where(function ($query) use ($cleanCode) {
                $query->where('verification_code', $cleanCode)
                    ->orWhere('report_number', $cleanCode);
            })
            ->first();

        if (!$report) {
            return [
                'valid' => false,
                'message' => 'INVALID OR UNVERIFIED REPORT',
                'details' => null,
            ];
        }

        // Audit check
        if ($report->case) {
            TribunalCaseEventService::log(
                $report->case,
                'tribunal_report_verification_checked',
                auth()->id(),
                [
                    'report_number' => $report->report_number,
                    'verification_code' => $report->verification_code,
                ]
            );
        }

        return [
            'valid' => true,
            'message' => 'VALID MYINTELLIBOOK_LIVE TRIBUNAL REPORT',
            'details' => [
                'report_number' => $report->report_number,
                'case_number' => $report->case?->case_number,
                'report_type' => $report->report_type,
                'issued_at' => $report->issued_at?->toIso8601String(),
                'issued_at_formatted' => $report->issued_at?->format('d F Y, H:i:s T'),
                'decision_number' => $report->decision?->decision_number,
                'decision_published_at' => $report->decision?->published_at?->toIso8601String(),
                'adjudicated_by' => $report->decision?->juryPanel?->panel_name,
                'status' => $report->status,
                'version' => $report->version,
                'file_hash' => $report->file_hash,
                'authenticity_confirmed' => true,
                'confirmation_statement' => 'Authentic determination rendered by Myintellibook_live Tribunal Division. Authenticity confirmed through official cryptographic record.',
            ],
        ];
    }

    /**
     * Verify uploaded PDF file hash against stored database hash.
     */
    public function verifyFile(UploadedFile $file, ?string $code = null): array
    {
        $fileHash = hash_file('sha256', $file->getRealPath());

        $query = TribunalCaseReport::with(['case', 'decision']);

        if ($code) {
            $cleanCode = trim(strtoupper($code));
            $query->where(function ($q) use ($cleanCode) {
                $q->where('verification_code', $cleanCode)
                    ->orWhere('report_number', $cleanCode);
            });
        } else {
            $query->where('file_hash', $fileHash);
        }

        $report = $query->first();

        if (!$report) {
            return [
                'valid_hash' => false,
                'calculated_hash' => $fileHash,
                'message' => 'No matching official Tribunal report found for this document.',
                'matched' => false,
            ];
        }

        $isMatch = hash_equals($report->file_hash, $fileHash);

        return [
            'valid_hash' => $isMatch,
            'calculated_hash' => $fileHash,
            'stored_hash' => $report->file_hash,
            'matched' => $isMatch,
            'report_number' => $report->report_number,
            'verification_code' => $report->verification_code,
            'status' => $report->status,
            'version' => $report->version,
            'message' => $isMatch
                ? 'Document SHA-256 cryptographic hash matches original official record.'
                : 'Document hash mismatch. The uploaded file has been modified or corrupted.',
        ];
    }

    /**
     * Build Safe Report Dossier (Strict whitelist of allowed case records).
     */
    public function buildDossier(
        TribunalCase $case,
        TribunalDecision $decision,
        string $reportNumber,
        string $verificationCode,
        string $qrDataUri,
        string $verifyUrl,
        int $version,
        \Carbon\CarbonInterface $issuedAt
    ): array {
        // 1. Parties
        $complainantUser = $case->parties()
            ->where('role', \App\Enums\TribunalPartyRole::Complainant)
            ->with('user.profile')
            ->first()?->user;

        $respondentUser = $case->parties()
            ->where('role', \App\Enums\TribunalPartyRole::Respondent)
            ->with('user.profile')
            ->first()?->user;

        $complainantName = $complainantUser?->profile
            ? trim("{$complainantUser->profile->first_name} {$complainantUser->profile->last_name}")
            : ($complainantUser?->name ?? 'Complainant');

        $respondentName = $respondentUser?->profile
            ? trim("{$respondentUser->profile->first_name} {$respondentUser->profile->last_name}")
            : ($respondentUser?->name ?? 'Respondent');

        // Representatives
        $representatives = [];
        foreach ($case->activeRepresentativeAssignments()->with(['representative.profile', 'representative.latestProfessionalVerification'])->get() as $rep) {
            $repUser = $rep->representative;
            $name = $repUser?->profile
                ? trim("{$repUser->profile->first_name} {$repUser->profile->last_name}")
                : ($repUser?->name ?? 'Legal Representative');

            $side = $case->isComplainant($rep->client_user_id) ? 'Complainant' : 'Respondent';
            $barNumber = $repUser?->latestProfessionalVerification?->registration_number;

            $representatives[] = [
                'name' => $name,
                'side' => $side,
                'bar_number' => $barNumber,
                'law_firm' => $repUser?->latestProfessionalVerification?->organization_name,
            ];
        }

        // 2. Formal Response
        $caseResponse = $case->caseResponse;
        $responseData = null;
        if ($caseResponse) {
            $responseData = [
                'position' => $caseResponse->position?->value ?? (string) $caseResponse->position,
                'response_text' => $caseResponse->response_text,
                'submitted_at' => $caseResponse->submitted_at?->format('d M Y, H:i T'),
            ];
        }

        // 3. Procedural History Milestones
        $proceduralHistory = $this->buildProceduralHistory($case, $decision);

        // 4. Evidence Index (Safe metadata only, NO storage paths)
        $evidenceIndex = [];
        foreach ($case->evidence()->orderBy('id')->get() as $ev) {
            $uploader = $ev->uploader;
            $uploaderName = $uploader?->profile
                ? trim("{$uploader->profile->first_name} {$uploader->profile->last_name}")
                : ($uploader?->name ?? 'Party');

            $evidenceIndex[] = [
                'evidence_number' => $ev->evidence_number,
                'type' => $ev->type?->value ?? (string) $ev->type,
                'title' => $ev->title,
                'description' => $ev->description,
                'submitted_by' => $uploaderName,
                'submitted_at' => $ev->submitted_at?->format('d M Y'),
                'status' => $ev->status?->value ?? (string) $ev->status,
            ];
        }

        // 5. Witnesses
        $witnesses = [];
        foreach ($case->witnesses()->whereIn('status', [\App\Enums\TribunalWitnessStatus::Approved])->get() as $w) {
            $witnesses[] = [
                'witness_name' => $w->witness_name,
                'side' => $w->side ? ucfirst($w->side) : 'Neutral',
                'status' => $w->status?->value ?? (string) $w->status,
                'relationship' => $w->relationship_to_case,
                'statement_summary' => $w->statement_summary,
            ];
        }

        // 6. Hearings & Official Record Entries
        $hearings = [];
        foreach ($case->hearings()->orderBy('scheduled_at', 'asc')->get() as $h) {
            $entries = [];
            foreach ($h->entries()->orderBy('sequence_number', 'asc')->get() as $entry) {
                $sender = $entry->sender;
                $speakerName = $sender?->profile
                    ? trim("{$sender->profile->first_name} {$sender->profile->last_name}")
                    : ($sender?->name ?? 'Participant');

                $entries[] = [
                    'sequence_number' => $entry->sequence_number,
                    'entry_type' => $entry->entry_type?->value ?? (string) $entry->entry_type,
                    'speaker_name' => $speakerName,
                    'participant_type' => $entry->participant_type,
                    'side' => $entry->side,
                    'body' => $entry->body,
                    'created_at' => $entry->created_at?->format('d M Y, H:i T'),
                ];
            }

            $hearings[] = [
                'hearing_number' => $h->hearing_number,
                'hearing_type' => $h->hearing_type?->value ?? (string) $h->hearing_type,
                'status' => $h->status?->value ?? (string) $h->status,
                'scheduled_at' => $h->scheduled_at?->format('d M Y, H:i T'),
                'started_at' => $h->started_at?->format('d M Y, H:i T'),
                'ended_at' => $h->ended_at?->format('d M Y, H:i T'),
                'entries' => $entries,
            ];
        }

        // 7. Findings (Public ONLY)
        $findings = [];
        foreach ($case->findings()->where('is_public', true)->with(['evidence', 'witnesses'])->orderBy('display_order')->get() as $f) {
            $findings[] = [
                'finding_number' => $f->finding_number,
                'finding_type' => $f->finding_type?->value ?? (string) $f->finding_type,
                'title' => $f->title,
                'finding_text' => $f->finding_text,
                'conclusion' => $f->conclusion?->value ?? (string) $f->conclusion,
                'cited_evidence' => $f->evidence->pluck('evidence_number')->all(),
                'cited_witnesses' => $f->witnesses->pluck('witness_name')->all(),
            ];
        }

        // 8. Orders / Remedies
        $orders = [];
        foreach ($decision->orders()->orderBy('id')->get() as $o) {
            $orders[] = [
                'order_number' => $o->order_number,
                'order_type' => $o->order_type?->value ?? (string) $o->order_type,
                'title' => $o->title,
                'description' => $o->description,
                'target_side' => $o->target_side ? ucfirst($o->target_side) : null,
                'deadline_at' => $o->deadline_at?->format('d M Y'),
                'status' => $o->status?->value ?? (string) $o->status,
            ];
        }

        // 9. Jury Panel Adjudicators
        $panel = $decision->juryPanel;

        return [
            // Metadata
            'report_number' => $reportNumber,
            'verification_code' => $verificationCode,
            'version' => $version,
            'issued_at' => $issuedAt->format('d F Y, H:i:s T'),
            'qr_data_uri' => $qrDataUri,
            'verify_url' => $verifyUrl,

            // Case Info
            'case_number' => $case->case_number,
            'case_title' => $case->title,
            'category' => $case->category,
            'severity' => $case->severity,
            'case_status' => $case->status?->value ?? (string) $case->status,
            'submitted_at' => $case->submitted_at?->format('d F Y') ?? $case->created_at?->format('d F Y'),

            // Parties
            'complainant_name' => $complainantName,
            'respondent_name' => $respondentName,
            'representatives' => $representatives,

            // Complaint & Response
            'complaint_description' => $case->description,
            'requested_resolution' => $case->requested_resolution,
            'respondent_response' => $responseData,

            // Proceedings
            'procedural_history' => $proceduralHistory,
            'evidence_index' => $evidenceIndex,
            'witnesses' => $witnesses,
            'hearings' => $hearings,

            // Determinations
            'findings' => $findings,
            'decision_number' => $decision->decision_number,
            'decision_outcome' => $decision->outcome?->value ?? (string) $decision->outcome,
            'decision_summary' => $decision->summary,
            'decision_reasoning' => $decision->reasoning,
            'decision_published_at' => $decision->published_at?->format('d F Y, H:i T'),
            'adjudicated_by' => $panel ? "{$panel->panel_name} ({$panel->panel_code})" : 'Jury Panel',
            'orders' => $orders,

            // Appeal
            'appeal_deadline' => $decision->appeal_deadline?->format('d F Y, H:i T'),
            'appeal_status' => $case->status === \App\Enums\TribunalCaseStatus::Appealed
                ? 'Formal Appeal Filed'
                : ($decision->appeal_deadline && now()->lessThan($decision->appeal_deadline)
                    ? 'Appeal Window Open'
                    : 'Appeal Window Concluded'),
        ];
    }

    /**
     * Build procedural history milestones safely.
     */
    protected function buildProceduralHistory(TribunalCase $case, TribunalDecision $decision): array
    {
        $events = [];

        // 1. Case Filed
        $filedDate = $case->submitted_at ?? $case->created_at;
        $events[] = [
            'date' => $filedDate ? $filedDate->format('d M Y') : 'Unknown',
            'stage' => 'Case Filed',
            'description' => "Dispute formally submitted under Case Number {$case->case_number}.",
        ];

        // 2. Response Submitted
        if ($case->response) {
            $events[] = [
                'date' => $case->response->submitted_at ? $case->response->submitted_at->format('d M Y') : 'Recorded',
                'stage' => 'Formal Response Submitted',
                'description' => "Respondent entered formal position: " . ucfirst((string) $case->response->position?->value ?? (string) $case->response->position) . '.',
            ];
        }

        // 3. Panel Assignment
        $assignment = $case->juryPanelAssignments()->first();
        if ($assignment) {
            $events[] = [
                'date' => $assignment->assigned_at ? $assignment->assigned_at->format('d M Y') : $assignment->created_at->format('d M Y'),
                'stage' => 'Jury Panel Assigned',
                'description' => 'Dispute referred to official Jury Panel for judicial oversight.',
            ];
        }

        // 4. Mediation if conducted
        $mediation = $case->mediations()->first();
        if ($mediation) {
            $events[] = [
                'date' => $mediation->created_at->format('d M Y'),
                'stage' => 'Mediation Facilitation',
                'description' => "Alternative dispute resolution conducted (Status: " . ucfirst((string) $mediation->status?->value ?? (string) $mediation->status) . ').',
            ];
        }

        // 5. Hearings
        foreach ($case->hearings as $h) {
            $events[] = [
                'date' => $h->scheduled_at ? $h->scheduled_at->format('d M Y') : $h->created_at->format('d M Y'),
                'stage' => "Hearing {$h->hearing_number}",
                'description' => "Formal hearing session held (Type: " . ucfirst((string) $h->hearing_type?->value ?? (string) $h->hearing_type) . ").",
            ];
        }

        // 6. Decision Published
        if ($decision->published_at) {
            $events[] = [
                'date' => $decision->published_at->format('d M Y'),
                'stage' => 'Final Decision Published',
                'description' => "Tribunal Decision {$decision->decision_number} published. Outcome: " . str_replace('_', ' ', ucfirst((string) $decision->outcome?->value ?? (string) $decision->outcome)) . '.',
            ];
        }

        return $events;
    }

    /**
     * Atomically generate unique report number MIB-RPT-{YEAR}-{000001}.
     */
    protected function generateReportNumber(): string
    {
        $year = now()->year;

        $latest = TribunalCaseReport::where('report_number', 'like', "MIB-RPT-{$year}-%")
            ->lockForUpdate()
            ->orderByDesc('id')
            ->first();

        $seq = 1;
        if ($latest && preg_match('/MIB-RPT-\d+-(\d+)/', $latest->report_number, $matches)) {
            $seq = (int) $matches[1] + 1;
        }

        return sprintf("MIB-RPT-%d-%06d", $year, $seq);
    }

    /**
     * Generate secure random human-readable verification code: VER-XXXX-XXXX.
     */
    protected function generateVerificationCode(): string
    {
        // Safe characters excluding confusing characters: digits and uppercase letters
        $chars = '23456789ABCDEFGHJKLMNPQRSTUVWXYZ';

        do {
            $p1 = '';
            $p2 = '';
            for ($i = 0; $i < 4; $i++) {
                $p1 .= $chars[random_int(0, strlen($chars) - 1)];
                $p2 .= $chars[random_int(0, strlen($chars) - 1)];
            }
            $code = "VER-{$p1}-{$p2}";
        } while (TribunalCaseReport::where('verification_code', $code)->exists());

        return $code;
    }
}
